alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'microservices'
      metrics_path: '/actuator/prometheus'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app]
          action: keep
          regex: 'userservice|bookservice|configservice'
