apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
  type: NodePort

#apiVersion: v1
#kind: Service
#metadata:
#  name: jenkins
#spec:
#  type: NodePort
#  ports:
#    - port: 8080
#      targetPort: 8080
#      nodePort: 30000
#  selector:
#    app: jenkins-dind