apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
    spec:
      containers:
        - name: configservice
          imagePullPolicy: Always
          image: shifer/microservice-configservice:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
      automountServiceAccountToken: false